### ISSUE TITLE
Required setup issue

### ISSUE THREAD

**Issue by Copyrght** [btactic/zimbra-ose-2fa#4]
Hi! Just installed your 2fa on Zimbra 10.0.5, and it work great, but had some issue. If i turn on require 2fa for user, on page when user need to start setup button "start setup" dont work, just nothing happens. In console i got this error:

`TwoFactor_all.js.zgz?v=231020115801:32 Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at twofactorauth_qr_setup (TwoFactor_qr.js.zgz?v=231020115801:34:54)
    at ZmTwoFactorSetupDialog._beginSetupButtonListener (TwoFactor_qr.js.zgz?v=231020115801:64:9)
    at Function.run ((index):722:47)
    at DwtDialog._runCallbackForButtonId (TwoFactor_all.js.zgz?v=231020115801:5203:7)
    at DwtDialog._buttonListener (TwoFactor_all.js.zgz?v=231020115801:5197:12)
    at AjxCallback.run ((index):755:33)
    at AjxListener.handleEvent (TwoFactor_all.js.zgz?v=231020115801:87:59)
    at AjxEventMgr.notifyListeners (TwoFactor_all.js.zgz?v=231020115801:57:20)
    at DwtControl.notifyListeners (TwoFactor_all.js.zgz?v=231020115801:3830:74)
    at DwtButton._handleClick (TwoFactor_all.js.zgz?v=231020115801:5726:6)`

**Comment by adriangibanelbtactic** [comment]
This might be the same error that @imanudin11 reported on https://github.com/btactic/zimbra-ose-2fa/issues/1#issuecomment-1774925660 .

The correct fix is to find out an alternative way to find the 2FA box for Zimbra 10 and switch between those ways depending on what it's found when the script is run.

In the meanwhile you can revert this specific part (you only lose the QR on this Required Setup dialog) by doing:
```
cp /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp
```
.

Having access to a Zimbra 10 installation would help.

**Comment by Copyrght** [comment]
Without QR it works. If you need some code from Zimbra 10 files, i can provide it

**Comment by adriangibanelbtactic** [comment]
Let's see if you can test: https://github.com/btactic/zimbra-ose-2fa/commit/c6397131943552e866f199b3fd9b36f9952d42bd which I have rushed to write.

So basically just before you are about to install you need to override your TwoFactor_qr.js with the fixed one.

So first of all you need to undo the QR addon installation completely (you only undid one of the two here):
```
cp /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp
cp /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js
```
.

Then something like this:

```
sudo -i # Become root
cd /tmp
wget 'https://github.com/btactic/zimbra-ose-2fa/releases/download/v0.7.0/zimbra-ose-2fa_0.7.0.tar.gz'
tar xzf zimbra-ose-2fa_0.7.0.tar.gz
cd zimbra-ose-2fa_0.7.0
wget 'https://raw.githubusercontent.com/btactic/zimbra-ose-2fa/c6397131943552e866f199b3fd9b36f9952d42bd/qr/TwoFactor_qr.js' -O qr/TwoFactor_qr.js
./install.sh
```

I am very interested on having screenshots:
- For this Required Setup page
- From Classic UI when enabling it from preferences
- From Modern UI when enabling it from preferences
.

Thank you for your feedback.

**Comment by Copyrght** [comment]
Looks like now it works. But i cant provide you screenshots of modern UI preferences because i use FOSS edition. 

Required setup page:

![qr_req](https://github.com/btactic/zimbra-ose-2fa/assets/57133235/ac186a73-5b6a-453e-8ba4-9254aa39d90c)

Classic UI preferences page:

![qr_pref](https://github.com/btactic/zimbra-ose-2fa/assets/57133235/aed95d9a-613a-426b-9da3-6bd69d8e46cc)

**Comment by Copyrght** [comment]
Looks like now it works! But i cant provide you screenshot of modern UI preferences page, because i use FOSS edition.

Required setup page:

![qr_reqs](https://github.com/btactic/zimbra-ose-2fa/assets/57133235/a84aea38-0536-415c-aa1f-8f73bd77045d)

Classic UI preferences page:

![qr_prefs](https://github.com/btactic/zimbra-ose-2fa/assets/57133235/b7d91228-0ced-41aa-b9a4-97df3fee4a13)

**Comment by adriangibanelbtactic** [comment]
> Looks like now it works! But i cant provide you screenshot of modern UI preferences page, because i use FOSS edition.
> 
> Required setup page:
> 
> ![qr_reqs](https://user-images.githubusercontent.com/57133235/279639909-a84aea38-0536-415c-aa1f-8f73bd77045d.png)
> 
> Classic UI preferences page:
> 
> ![qr_prefs](https://user-images.githubusercontent.com/57133235/279639927-b7d91228-0ced-41aa-b9a4-97df3fee4a13.png)

That's perfect. It seems that we might officially announce that both Zimbra 9 FOSS and Zimbra 10 FOSS are also supported.
