### ISSUE TITLE
shows me the key and not the qr code image

### ISSUE THREAD

**Issue by G1anko** [btactic/zimbra-ose-2fa#5]
It is very good!
It only shows me the key and not the qr code image. Has the problem occurred to others?
(Release 8.8.15_GA_3953.RHEL8_64_20200629025823 RHEL8_64 FOSS edition, Patch 8.8.15_P44.)
![noqr](https://github.com/btactic/zimbra-ose-2fa/assets/126389141/53a83c65-e764-4c1a-ada3-b2c5cd772a26)
I had tried to install version 0.6.0 before...
At the same time I have also installed Zimbra open source two factor authentication with PrivacyIDEA and it shows the qr code image.
I tried in a virtual machine with all the same (Release 8.8.15_GA_3953.RHEL8_64_20200629025823 RHEL8_64 FOSS edition, Patch 8.8.15_P41 and at the same time 2FA PrivacyIDEA) and the image of the qr code appears!
I must have changed something...

**Comment by G1anko** [comment]
With an update from P41 to P43, the qr image stopped appearing in the virtual machine as well.
I installed 2FA again in the virtual machine and the qr image appeared.

**Comment by adriangibanelbtactic** [comment]
> At the same time I have also installed Zimbra open source two factor authentication with PrivacyIDEA and it shows the qr code image.

[Zimbra Open Source Two Factor Authentication with PrivacyIDEA](https://github.com/Zimbra-Community/zimbra-foss-2fa#zimbra-open-source-two-factor-authentication-with-privacyidea) project is a completely different project.

The 2FA codes are not saved into Zimbra itself but in PrivacyIDEA which has a 50 users limit in its open version. It is not compatible with this implementation.

So if you are going to use this zimbra-ose-2fa implementation you should remove manually the PrivacyIDEA one first.

**Comment by adriangibanelbtactic** [comment]
> I tried in a virtual machine with all the same
> (Release 8.8.15_GA_3953.RHEL8_64_20200629025823 RHEL8_64 FOSS edition, Patch 8.8.15_P41
> and at the same time 2FA PrivacyIDEA) and the image of the qr code appears!
> I must have changed something...

As you can see in the [Additional notes](https://github.com/btactic/zimbra-ose-2fa/tree/v0.7.0#additional-notes) the QR addon modifies some stock Zimbra files.

So, yes, it's expected that you re-run the installer when some of those files are being updated/overwritten by the Zimbra update.

If you want to make sure that everything is reinstalled again the procedure is the following one:

- Run the installer
```
cp /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp
cp /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js
cp /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js.zgz_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js.zgz
```
- Run the installer again

**Comment by G1anko** [comment]
> 
> ```
> su - zimbra -c 'zmzimletctl undeploy com_btactic_twofactorauth_qr'
> ```
> before anything else.

I've done it many times
I will follow the instructions. Thanks!

**Comment by adriangibanelbtactic** [comment]
> So, yes, it's expected that you re-run the installer when some of those files are being updated/overwritten by the Zimbra update.

I'll try to add a section about Zimbra upgrades so this is better explained.

**Comment by adriangibanelbtactic** [comment]
> > ```
> > su - zimbra -c 'zmzimletctl undeploy com_btactic_twofactorauth_qr'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > before anything else.
> 
> I've done it many times I will follow the instructions. Thanks!

Yeah, hopefully the commands do the trick, otherwise you will have to figure out on your own what the PrivacyIdea installation changed on your system that it is now colliding/clashing with this implementation.

**Comment by G1anko** [comment]
Since the problem doesn't occur in the virtual machine with PrivacyIdea and Maldua running at the same time (the qr image appears fine in both), I wonder if the 0.6.0 version that was originally installed made changes that were not fixed by 0.7.0

**Comment by adriangibanelbtactic** [comment]
> Since the problem doesn't occur in the other VM with PrivacyIdea and Maldua running at the same time (the qr image appears fine in both)

That setup is not supported but ok.

> I wonder if the 0.6.0 version that was originally installed made changes that were not fixed by 0.7.0

The only thing different about 0.6.0 is the QR zimlet which you have already undeployed so you should be fine.

> Only these 3 zimbra files change?
> /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp
> /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js
> /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js.zgz

You can check what the installer does here: https://github.com/btactic/zimbra-ose-2fa/blob/v0.7.0/install.sh just in case I have missed anything.

**Comment by adriangibanelbtactic** [comment]
@G1anko Why you don't give a try to: https://github.com/btactic/zimbra-ose-2fa/issues/4#issuecomment-1787607097 ?

Maybe the most recent patch has updated some of the 2FA code and it's more similar to Zimbra 9/Zimbra 10 codebase.
It's safe to test because that specific change should work for 8.8.15 too.

**Comment by G1anko** [comment]
I tried to clear the chrome cache today and the qr image appeared! I had a feeling I had tried it before I wrote to you, but it didn't work then. 0.6.6 seems to have left its mark on chrome...
Maldua's 2fa works great! Sorry for the inconvenience! Thanks a lot for your time!

**Comment by G1anko** [comment]
> * Run the installer
> 
> ```
> cp /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/public/TwoFactorSetup.jsp
> cp /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js
> cp /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js.zgz_2FAQR_COPY /opt/zimbra/jetty/webapps/zimbra/js/Preferences_all.js.zgz
> ```
> 
> * Run the installer again

but it is very likely also due to a recent oracle linux update or the above commands I gave again. I am confused...
Maldua's 2fa works great!

**Comment by adriangibanelbtactic** [comment]
> I tried to clear the chrome cache today and the qr image appeared! I had a feeling I had tried it before I wrote to you, but it didn't work then. 0.6.0 seems to have left its mark on chrome... Maldua's 2fa works great! Sorry for the inconvenience! Thanks a lot for your time!

Yes, you always have to make additional tests with a different Internet browser than the usual one and in incognito/private mode.

I'm glad it finally worked for you.
