### ISSUE TITLE
Whitelist specific IPs?

### ISSUE THREAD

**Issue by KlugFR** [btactic/zimbra-ose-2fa#8]
Hello.

Is there a way to whitelist private LAN IPs?
Or specific public IP per domain in case of hosted Zimbra server?

The idea would be "you do MFA if you're home or away but when in the office, the login is standard".

**Comment by adriangibanelbtactic** [comment]
That's similar to a Zextras 2FA feature.

I don't think that's a feature even from Zimbra NE 2FA.

Is trusting devices as described here: [https://wiki.zimbra.com/wiki/Zimbra_Two-factor_authentication#Trusted_Devices](https://wiki.zimbra.com/wiki/Zimbra_Two-factor_authentication#Trusted_Devices) enough for your use case?

**Comment by KlugFR** [comment]
Hi.

Trusted devices could fit in.
We'll check with end user, thank you.
